// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Contexts;

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190102191914_migr1")]
    partial class migr1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Models.Entities.Allocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AllocationDateTime");

                    b.Property<double>("Amount");

                    b.Property<int>("BudgetCategoryId");

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("AllocationId");

                    b.HasIndex("BudgetCategoryId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Currency");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("StartingDate");

                    b.Property<int>("UserId");

                    b.HasKey("BudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("WebApi.Models.Entities.BudgetCategory", b =>
                {
                    b.Property<int>("BudgetCategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BudgetId");

                    b.Property<string>("Icon")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("BudgetCategoryId");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("WebApi.Models.Entities.BudgetCategoryAmountConfig", b =>
                {
                    b.Property<int>("BudgetCategoryAmountConfigId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BudgetCategoryId");

                    b.Property<double>("MonthlyAmount");

                    b.Property<DateTime>("ValidFrom");

                    b.Property<DateTime?>("ValidTo");

                    b.HasKey("BudgetCategoryAmountConfigId");

                    b.HasIndex("BudgetCategoryId");

                    b.ToTable("BudgetCategoryAmountConfigs");
                });

            modelBuilder.Entity("WebApi.Models.Entities.PasswordChange", b =>
                {
                    b.Property<int>("PasswordChangeId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ChangeDateTime");

                    b.Property<int>("UserId");

                    b.HasKey("PasswordChangeId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordChanges");
                });

            modelBuilder.Entity("WebApi.Models.Entities.PasswordReset", b =>
                {
                    b.Property<int>("PasswordResetId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("GenerationDateTime");

                    b.Property<string>("Token")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.HasKey("PasswordResetId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("WebApi.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId")
                        .IsRequired();

                    b.Property<string>("Token")
                        .IsRequired();

                    b.Property<int>("UserId");

                    b.Property<DateTime>("ValidTo");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<int>("BudgetCategoryId");

                    b.Property<int>("CreatedByUserId");

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("TransactionDateTime");

                    b.HasKey("TransactionId");

                    b.HasIndex("BudgetCategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WebApi.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<int?>("DefaultBudgetId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<DateTime?>("EmailVerifiedTime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(160);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Role");

                    b.Property<int>("UserId");

                    b.HasKey("UserRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ZNetCS.AspNetCore.Logging.EntityFrameworkCore.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EventId");

                    b.Property<int>("Level");

                    b.Property<string>("Message");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<DateTimeOffset>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("WebApi.Models.Entities.Allocation", b =>
                {
                    b.HasOne("WebApi.Models.Entities.BudgetCategory", "BudgetCategory")
                        .WithMany("Allocations")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.Budget", b =>
                {
                    b.HasOne("WebApi.Models.Entities.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.BudgetCategory", b =>
                {
                    b.HasOne("WebApi.Models.Entities.Budget", "Budget")
                        .WithMany("BudgetCategories")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.BudgetCategoryAmountConfig", b =>
                {
                    b.HasOne("WebApi.Models.Entities.BudgetCategory", "BudgetCategory")
                        .WithMany("BudgetCategoryAmountConfigs")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.PasswordChange", b =>
                {
                    b.HasOne("WebApi.Models.Entities.User", "User")
                        .WithMany("PasswordChanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.PasswordReset", b =>
                {
                    b.HasOne("WebApi.Models.Entities.User", "User")
                        .WithMany("PasswordResets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("WebApi.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.Transaction", b =>
                {
                    b.HasOne("WebApi.Models.Entities.BudgetCategory", "BudgetCategory")
                        .WithMany("Transactions")
                        .HasForeignKey("BudgetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Models.Entities.UserRole", b =>
                {
                    b.HasOne("WebApi.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
